default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: MyDatabase
  host: localhost
  pool: 5
  username: postgres
  password: Rohit@123

test:
  <<: *default
  database: postgresApp_test

production:
  adapter: postgresql
  encoding: unicode
  database: MyDatabase_Production
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['MyDatabase_Password'] %>
  role: MyRole
